"""Write the hand-upload kit (docs/publish-kit-2026-10.md) from every scheduled, packaged episode of the given channels.

    python3 studio/tools/publish_kit.py why-map body-cast

Reads each episode's package.json (title, description, hashtags, tags, schedule, pinned comment, related video) and
build/final_report.json (measured numbers). The API-audit section at the end of the existing kit is kept as is.
"""
import json, os, sys
from datetime import datetime
from zoneinfo import ZoneInfo

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "docs", "publish-kit-2026-10.md")
chans = sys.argv[1:] or ["why-map", "body-cast"]
names = {c: json.load(open(os.path.join(ROOT, "studio", "channels", c, "bible.json")))["name"] for c in chans}

eps = []
for c in chans:
    base = os.path.join(ROOT, "episodes", c)
    for slug in sorted(os.listdir(base)):
        d = os.path.join(base, slug)
        if not os.path.exists(os.path.join(d, "package.json")):
            continue
        pkg = json.load(open(os.path.join(d, "package.json")))
        if not pkg.get("schedule"):
            continue
        fr = os.path.join(d, "build", "final_report.json")
        eps.append((pkg["schedule"], c, slug, pkg, json.load(open(fr)) if os.path.exists(fr) else {}))
eps.sort()

audit = ""
if os.path.exists(OUT):
    old = open(OUT).read()
    i = old.find("## YouTube API audit")
    audit = old[i:] if i >= 0 else ""


def et(utc):
    t = datetime.fromisoformat(utc.replace("Z", "+00:00")).astimezone(ZoneInfo("America/New_York"))
    return t.strftime("%a %-d %b, %H:%M")


rel = lambda c, s, f: f"episodes/{c}/{s}/{f}"
L = [f"# Publish kit: {' and '.join(names[c] for c in chans)} ({len(eps)} Shorts, October-November 2026)", "",
     "Everything needed to upload each video by hand in YouTube Studio. API uploads stay off until the API audit passes",
     "(an unverified project's API uploads are locked private for good). Generated by `studio/tools/publish_kit.py`.", "",
     "**Where the files are:** the dashboard plays and links the exact full-quality MP4s; captions and thumbnails are in",
     "each episode's `out/` folder (also on the dashboard).", "",
     "**You can upload all of them today:** Studio → Create → Upload → pick the MP4 → paste the title and description →",
     "add the thumbnail → Audience: *No, it's not made for kids* → Altered content: *No* (it's animation) → upload the SRT",
     "under Subtitles → Visibility: **Schedule**, at the time below (your Studio time zone may differ; the UTC time is",
     "exact). After each goes live, post the pinned comment and pin it, and set the related video. Then run",
     "`python3 studio/tools/channel_setup.py sort` (or ask me) to file each Short into its series playlist.", "",
     "| # | When (ET) | UTC | Channel | Title | Length | Voice |", "|---|---|---|---|---|---|---|"]
for n, (s, c, slug, pkg, fr) in enumerate(eps, 1):
    voice = "Hannah (Fish)" if "Hannah" in pkg.get("synthetic_media", {}).get("voice", "") else "George (Kokoro)"
    L.append(f"| {n} | {et(s)} | {s} | {names[c]} | {pkg['title']} | {fr.get('duration', '?')} s | {voice} |")
for n, (s, c, slug, pkg, fr) in enumerate(eps, 1):
    desc = pkg["description"] + ("\n\n" + " ".join(pkg["hashtags"]) if pkg.get("hashtags") else "")
    L += ["", f"## {n}. {names[c]}: {pkg['title']}", "",
          f"- **Schedule:** {et(s)} ET ({s})",
          f"- **Video:** `{rel(c, slug, pkg['video'])}`  **Captions:** `{rel(c, slug, pkg['srt'])}`  **Thumbnail:** `{rel(c, slug, pkg['thumbnail'])}`",
          f"- **Hashtags** (already at the end of the description): {' '.join(pkg.get('hashtags', []))}",
          f"- **Tags** (Studio → Show more → Tags): {', '.join(pkg.get('tags', []))}",
          f"- **Category:** {pkg.get('category', 'Education')} · **Language:** English · **Made for kids:** No",
          f"- **Related video** (Studio → the Short → Related video, once both are up): {pkg.get('related_video', '')}",
          f"- **Pinned comment:** {pkg.get('pinned_comment', '')}",
          f"- **Measured:** {fr.get('width')}×{fr.get('height')}, {fr.get('fps')} fps, {fr.get('lufs')} LUFS, transcript WER {fr.get('wer')}",
          "", "**Description:**", "", "```", desc, "```"]
open(OUT, "w").write("\n".join(L) + ("\n\n" + audit if audit else "\n"))
print(f"wrote {os.path.relpath(OUT, ROOT)}: {len(eps)} Shorts")
